NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/root-ca-hlf-ca-svc-cluster-local-7054-root-ca.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/root-ca-hlf-ca-svc-cluster-local-7054-root-ca.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/root-ca-hlf-ca-svc-cluster-local-7054-root-ca.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/root-ca-hlf-ca-svc-cluster-local-7054-root-ca.pem
    OrganizationalUnitIdentifier: orderer