{{- $domain := .Values.domain -}}
{{- $root := . -}}
{{- range $i := until (.Values.replicaCount | int) }}
apiVersion: v1
kind: Secret
metadata:
  name: orderer{{ $i }}-tls
  namespace: {{ $root.Values.namespace }}
type: Opaque
data:
  server.crt: {{ $root.Files.Get (printf "files/crypto/ordererOrganizations/%s/orderers/orderer%d.%s/tls/server.crt" $domain $i $domain) | b64enc }}
  server.key: {{ $root.Files.Get (printf "files/crypto/ordererOrganizations/%s/orderers/orderer%d.%s/tls/server.key" $domain $i $domain) | b64enc }}
  ca.crt:     {{ $root.Files.Get (printf "files/crypto/ordererOrganizations/%s/orderers/orderer%d.%s/tls/ca.crt"     $domain $i $domain) | b64enc }}
---
{{- end }}

