{{- $domain := .Values.domain -}}
{{- $root := . -}}
{{- range $i := until (.Values.replicaCount | int) }}
{{- $mspPath := printf "files/crypto/ordererOrganizations/%s/orderers/orderer%d.%s/msp" $domain $i $domain }}
apiVersion: v1
kind: Secret
metadata:
  name: orderer{{ $i }}-msp
  namespace: {{ $root.Values.namespace }}
type: Opaque
data:
  {{- range $file, $content := $root.Files.Glob (printf "%s/*" $mspPath) }}
  {{ base $file }}: {{ $content | b64enc }}
  {{- end }}
---
{{- end }}

