{{- range .Values.orderer.nodes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  serviceName: {{ .name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: orderer
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["orderer"]
          ports:
            - containerPort: 7050
              name: grpc
          env:
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "{{ $.Values.orderer.mspID }}"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /var/hyperledger/tls/server.key
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /var/hyperledger/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/var/hyperledger/tls/ca.crt]"
            - name: ORDERER_FILELEDGER_LOCATION
              value: /var/hyperledger/production
            - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
              value: "file"
            - name: ORDERER_GENERAL_BOOTSTRAPFILE
              value: /var/hyperledger/genesis/genesis.block
          volumeMounts:
            - name: msp
              mountPath: /var/hyperledger/msp
            - name: tls
              mountPath: /var/hyperledger/tls
            - name: genesis
              mountPath: /var/hyperledger/genesis
            - name: data
              mountPath: /var/hyperledger/production
      volumes:
        - name: msp
          secret:
            secretName: {{ .mspSecret }}
        - name: tls
          secret:
            secretName: {{ .tlsSecret }}
        - name: genesis
          secret:
            secretName: {{ $.Values.genesis.secretName }}
            items:
              - key: {{ $.Values.genesis.fileKey }}
                path: genesis.block
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $.Values.persistence.size }}
{{- end }}

