intermediateCA:
  enabled: true
  name: verifier-ca
  namespace: hlf-ca

  image:
    repository: hyperledger/fabric-ca
    tag: 1.5.12
    pullPolicy: IfNotPresent

  port: 7054

  storage:
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: do-block-storage
    pvcName: pvc-verifier-ca  # Added from second block

  parentID: verifier-ca
  parentSecret: verifiercapw
  parentHost: root-ca.hlf-ca.svc.cluster.local

  csr:
    cn: verifier-ca           # Added from second block
    hosts:
      - verifier-ca
      - verifier-ca.hlf-ca.svc.cluster.local
      - localhost

  tls:
    enabled: true
    secretName: verifier-ca-tls-cert

  msp:
    secretName: verifier-ca-msp

  bootstrapUser: verifier-ca
  bootstrapPassword: verifiercapw

  service:
    port: 7054