namespace: hyperledger-fabric

image:
  repository: hyperledger/fabric-orderer
  tag: 2.5
  pullPolicy: IfNotPresent

orderer:
  mspID: OrdererMSP
  nodes:
    - name: orderer0
      namespace: hyperledger-fabric
      mspSecret: orderer0-msp
      tlsSecret: orderer0-tls
    - name: orderer1
      namespace: hyperledger-fabric
      mspSecret: orderer1-msp
      tlsSecret: orderer1-tls
    - name: orderer2
      namespace: hyperledger-fabric
      mspSecret: orderer2-msp
      tlsSecret: orderer2-tls
    - name: orderer3
      namespace: hyperledger-fabric
      mspSecret: orderer3-msp
      tlsSecret: orderer3-tls
    - name: orderer4
      namespace: hyperledger-fabric
      mspSecret: orderer4-msp
      tlsSecret: orderer4-tls

genesis:
  secretName: orderer-genesis-block
  fileKey: genesis.block

persistence:
  size: 2Gi

